swagger: "2.0"
info:
  version: "1.0.0"
  title: "Transaction API"
  description: "Contains all API endpoints for future transactions"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: "/api/v1"
schemes:
  - "http"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /transaction:
    get:
      security:
        - Bearer: []
      tags:
        - "transaction"
      summary: "Get all transactions"
      description: "Returns a list of transactions"
      operationId: "getAllTransactions"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                format: "int64"
              message:
                type: "string"
              body:
                type: "array"
                items:
                  $ref: "#/definitions/Transaction"
        "500":
          description: "Internal Server Error"
  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - "transaction"
      summary: "Get transaction by id"
      description: "Returns a single transaction"
      operationId: "getTransactionById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of transaction to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                format: "int64"
              message:
                type: "string"
              body:
                $ref: "#/definitions/Transaction"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Transaction not found"
        "500":
          description: "Internal Server Error"
    put:
      security:
        - Bearer: []
      tags:
        - "transaction"
      summary: "Update description transaction"
      description: "Update the type and/or note of a transaction"
      operationId: "updateDescriptionTransaction"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of transaction to update"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Transaction object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/UpdateTransactionInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: "Invalid input"
        "404":
          description: "Transaction not found"
        "500":
          description: "Internal Server Error"
definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      userId:
        type: "integer"
        format: "int64"
      amount:
        type: "number"
        format: "float"
      description:
        type: "string"
      type: 
        type: "string"
      category: 
        type: "string"
      note:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
        example: "2018-07-18T05:00:00.000Z"
      updatedAt:
        type: "string"
        format: "date-time"
        example: "2018-07-18T05:00:00.000Z"
  UpdateTransactionInput:
    type: "object"
    properties:
      type:
        type: "string"
        description: "New type for the transaction"
      note:
        type: "string"
        description: "New note for the transaction"
        